import { useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { useFieldService } from "@/lib/field-service/field-service-provider";
import { EMPTY_CHECKLIST, type ChecklistValues } from "@/lib/field-service/types";

type ChecklistOption = { key: keyof ChecklistValues; title: string; subtitle: string };
const options: ChecklistOption[] = [{ key: "siteAccess", title: "Site access confirmed", subtitle: "Verify access and customer authorization." }, { key: "safetyCheck", title: "Safety check complete", subtitle: "Confirm safe conditions before servicing equipment." }, { key: "serviceComplete", title: "Service task complete", subtitle: "Mark only when required work has been completed." }];
export default function VisitScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id: string }>(); const { ready, workOrders, getVisitForOrder, saveVisit, completeVisit } = useFieldService(); const workOrder = useMemo(() => workOrders.find((item) => item.id === id), [id, workOrders]); const visit = workOrder ? getVisitForOrder(workOrder.id) : undefined; const [notes, setNotes] = useState(visit?.notes ?? ""); const [checklist, setChecklist] = useState<ChecklistValues>(visit?.checklist ?? EMPTY_CHECKLIST); const [saving, setSaving] = useState(false);
  if (!ready) return <ScreenContainer className="items-center justify-center"><ActivityIndicator size="large" color="#087E8B" /></ScreenContainer>;
  if (!workOrder) return <ScreenContainer className="items-center justify-center p-6"><Text style={styles.notFound}>This visit is not available on this device.</Text></ScreenContainer>;
  const toggle = (key: keyof ChecklistValues) => setChecklist((previous) => ({ ...previous, [key]: !previous[key] })); const save = async () => { setSaving(true); await saveVisit(workOrder.id, { notes, checklist }); setSaving(false); Alert.alert("Saved on this device", "Your visit progress is safely queued for synchronization."); }; const complete = async () => { if (!checklist.siteAccess || !checklist.safetyCheck) { Alert.alert("Complete the required checks", "Confirm site access and the safety check before completing this visit."); return; } setSaving(true); await completeVisit(workOrder.id, { notes, checklist }); setSaving(false); router.replace({ pathname: "/work-orders/[id]", params: { id: workOrder.id } }); };
  return <ScreenContainer containerClassName="bg-[#F5F8FA]" className="bg-[#F5F8FA]" edges={["top", "left", "right", "bottom"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled"><View style={styles.topBar}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.backButton, pressed && styles.pressed]}><IconSymbol name="arrow.left" size={21} color="#123047" /></Pressable><Text style={styles.topTitle}>Field visit</Text><View style={styles.spacer} /></View><Text style={styles.customer}>{workOrder.customerName}</Text><Text style={styles.site}>{workOrder.serviceSite}</Text><View style={styles.localNotice}><IconSymbol name="wifi.slash" size={16} color="#087E8B" /><Text style={styles.localNoticeText}>Changes are saved locally first and queued for sync.</Text></View><Text style={styles.sectionTitle}>Completion checklist</Text><View style={styles.checklistCard}>{options.map((option, index) => <Pressable key={option.key} onPress={() => toggle(option.key)} style={({ pressed }) => [styles.checkRow, index > 0 && styles.rowDivider, pressed && styles.pressed]}><View style={[styles.checkbox, checklist[option.key] && styles.checkboxChecked]}>{checklist[option.key] ? <IconSymbol name="checkmark.circle.fill" size={20} color="#FFFFFF" /> : null}</View><View style={styles.checkCopy}><Text style={styles.checkTitle}>{option.title}</Text><Text style={styles.checkSubtitle}>{option.subtitle}</Text></View></Pressable>)}</View><Text style={styles.sectionTitle}>Service notes</Text><TextInput value={notes} onChangeText={setNotes} placeholder="Record findings, repairs, parts used, or follow-up work…" placeholderTextColor="#94A3B8" multiline textAlignVertical="top" style={styles.notesInput} returnKeyType="done" /><Pressable onPress={save} disabled={saving} style={({ pressed }) => [styles.secondaryButton, (pressed || saving) && styles.pressed]}><Text style={styles.secondaryText}>{saving ? "Saving…" : "Save progress"}</Text></Pressable><Pressable onPress={complete} disabled={saving} style={({ pressed }) => [styles.primaryButton, (pressed || saving) && styles.primaryPressed]}><Text style={styles.primaryText}>{saving ? "Saving…" : "Complete visit"}</Text><IconSymbol name="checkmark.circle.fill" size={19} color="#FFFFFF" /></Pressable></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingBottom: 30 }, topBar: { paddingTop: 5, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, backButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E1EAEE", alignItems: "center", justifyContent: "center" }, topTitle: { color: "#123047", fontSize: 16, fontWeight: "800" }, spacer: { width: 40 }, customer: { color: "#123047", fontSize: 26, fontWeight: "800", marginTop: 23, lineHeight: 32 }, site: { color: "#64748B", fontSize: 15, marginTop: 3 }, localNotice: { flexDirection: "row", gap: 8, alignItems: "center", backgroundColor: "#E9F7F7", borderRadius: 12, padding: 11, marginTop: 16 }, localNoticeText: { flex: 1, color: "#41636B", fontSize: 12, lineHeight: 17, fontWeight: "600" }, sectionTitle: { color: "#123047", fontSize: 18, fontWeight: "800", marginTop: 24, marginBottom: 9 }, checklistCard: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E1EAEE", borderRadius: 16, overflow: "hidden" }, checkRow: { padding: 14, flexDirection: "row", alignItems: "center", gap: 11 }, rowDivider: { borderTopWidth: 1, borderTopColor: "#EAF0F3" }, checkbox: { width: 24, height: 24, borderRadius: 12, borderWidth: 1.5, borderColor: "#B4C3CC", alignItems: "center", justifyContent: "center" }, checkboxChecked: { backgroundColor: "#087E8B", borderColor: "#087E8B" }, checkCopy: { flex: 1 }, checkTitle: { color: "#123047", fontSize: 14, fontWeight: "800" }, checkSubtitle: { color: "#64748B", fontSize: 12, lineHeight: 17, marginTop: 2 }, notesInput: { minHeight: 124, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D8E3E8", borderRadius: 16, padding: 14, color: "#123047", fontSize: 14, lineHeight: 20 }, secondaryButton: { minHeight: 50, borderRadius: 14, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#9DB8C4", alignItems: "center", justifyContent: "center", marginTop: 18 }, secondaryText: { color: "#123047", fontSize: 15, fontWeight: "800" }, primaryButton: { minHeight: 52, borderRadius: 14, backgroundColor: "#087E8B", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, marginTop: 10 }, primaryText: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" }, pressed: { opacity: 0.64 }, primaryPressed: { opacity: 0.84, transform: [{ scale: 0.98 }] }, notFound: { color: "#64748B", fontSize: 15, textAlign: "center" } });
