import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { useFieldService } from "@/lib/field-service/field-service-provider";

export default function ConflictsScreen() {
  const router = useRouter(); const { ready, workOrders, resolveConflict } = useFieldService(); const conflicts = workOrders.filter((item) => item.syncState === "conflict");
  if (!ready) return <ScreenContainer className="items-center justify-center"><ActivityIndicator size="large" color="#087E8B" /></ScreenContainer>;
  return <ScreenContainer containerClassName="bg-[#F5F8FA]" className="bg-[#F5F8FA]" edges={["top", "left", "right", "bottom"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.topBar}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.backButton, pressed && styles.pressed]}><IconSymbol name="arrow.left" size={21} color="#123047" /></Pressable></View><View style={styles.iconWrap}><IconSymbol name="exclamationmark.triangle.fill" size={26} color="#B42318" /></View><Text style={styles.title}>Resolve changes</Text><Text style={styles.subtitle}>The dispatcher updated one or more records while a field edit was waiting to synchronize. Choose the version that should continue.</Text>{conflicts.length === 0 ? <View style={styles.empty}><IconSymbol name="checkmark.circle.fill" size={26} color="#197A42" /><Text style={styles.emptyText}>There are no active conflicts.</Text></View> : conflicts.map((workOrder) => <View key={workOrder.id} style={styles.card}><Text style={styles.customer}>{workOrder.customerName}</Text><Text style={styles.site}>{workOrder.serviceSite}</Text><View style={styles.comparison}><View style={styles.version}><Text style={styles.versionLabel}>YOUR FIELD VERSION</Text><Text style={styles.versionText}>{workOrder.description}</Text></View><View style={styles.version}><Text style={styles.versionLabel}>DISPATCHER VERSION</Text><Text style={styles.versionText}>{workOrder.description} Dispatcher has re-prioritized this visit.</Text></View></View><Pressable onPress={async () => { await resolveConflict(workOrder.id, true); router.back(); }} style={({ pressed }) => [styles.primaryButton, pressed && styles.primaryPressed]}><Text style={styles.primaryText}>Keep my field update</Text></Pressable><Pressable onPress={async () => { await resolveConflict(workOrder.id, false); router.back(); }} style={({ pressed }) => [styles.secondaryButton, pressed && styles.pressed]}><Text style={styles.secondaryText}>Accept dispatcher update</Text></Pressable></View>)}</ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingBottom: 30 }, topBar: { paddingTop: 5 }, backButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E1EAEE", alignItems: "center", justifyContent: "center" }, iconWrap: { width: 52, height: 52, borderRadius: 26, backgroundColor: "#FDE8E7", alignItems: "center", justifyContent: "center", marginTop: 24 }, title: { color: "#123047", fontSize: 29, fontWeight: "800", marginTop: 14 }, subtitle: { color: "#64748B", fontSize: 14, lineHeight: 20, marginTop: 6 }, card: { backgroundColor: "#FFFFFF", borderRadius: 16, padding: 15, borderWidth: 1, borderColor: "#E1EAEE", marginTop: 20 }, customer: { color: "#123047", fontSize: 17, fontWeight: "800" }, site: { color: "#64748B", fontSize: 13, marginTop: 3 }, comparison: { gap: 9, marginTop: 15 }, version: { backgroundColor: "#F7FAFB", borderRadius: 12, padding: 12, borderWidth: 1, borderColor: "#E6EDF2" }, versionLabel: { color: "#64748B", fontSize: 10, fontWeight: "800", letterSpacing: 0.7 }, versionText: { color: "#334155", fontSize: 13, lineHeight: 18, marginTop: 5 }, primaryButton: { minHeight: 50, borderRadius: 13, backgroundColor: "#087E8B", alignItems: "center", justifyContent: "center", marginTop: 16 }, primaryText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" }, secondaryButton: { minHeight: 50, borderRadius: 13, alignItems: "center", justifyContent: "center", marginTop: 9 }, secondaryText: { color: "#123047", fontSize: 14, fontWeight: "800" }, empty: { alignItems: "center", backgroundColor: "#FFFFFF", borderRadius: 16, borderWidth: 1, borderColor: "#E1EAEE", padding: 24, gap: 8, marginTop: 20 }, emptyText: { color: "#64748B", fontSize: 14 }, pressed: { opacity: 0.64 }, primaryPressed: { opacity: 0.84, transform: [{ scale: 0.98 }] } });
