import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { startOAuthLogin } from "@/constants/oauth";
import { useAuth } from "@/hooks/use-auth";
import { useFieldService } from "@/lib/field-service/field-service-provider";

export default function ProfileScreen() {
  const router = useRouter(); const { user, loading, isAuthenticated, logout } = useAuth(); const { syncSummary } = useFieldService();
  return <ScreenContainer containerClassName="bg-[#F5F8FA]" className="bg-[#F5F8FA]" edges={["top", "left", "right", "bottom"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.topBar}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.backButton, pressed && styles.pressed]}><IconSymbol name="arrow.left" size={21} color="#123047" /></Pressable></View><Text style={styles.eyebrow}>TECHNICIAN PROFILE</Text><Text style={styles.title}>Workspace</Text>{loading ? <View style={styles.loader}><ActivityIndicator color="#087E8B" /></View> : <View style={styles.identityCard}><View style={styles.avatar}><IconSymbol name="person.fill" size={28} color="#FFFFFF" /></View><View style={styles.identityCopy}><Text style={styles.name}>{isAuthenticated ? user?.name ?? "Field technician" : "Offline workspace"}</Text><Text style={styles.email}>{isAuthenticated ? user?.email ?? "Authenticated technician" : "Sign in to securely synchronize assigned work."}</Text></View></View>}<Text style={styles.sectionTitle}>Data safeguards</Text><View style={styles.settingCard}><View style={styles.settingIcon}><IconSymbol name="wifi.slash" size={18} color="#087E8B" /></View><View style={styles.settingCopy}><Text style={styles.settingTitle}>Local first</Text><Text style={styles.settingText}>Field updates are committed to SQLite before any connection is required.</Text></View></View><View style={styles.settingCard}><View style={styles.settingIcon}><IconSymbol name="arrow.triangle.2.circlepath" size={18} color="#087E8B" /></View><View style={styles.settingCopy}><Text style={styles.settingTitle}>Synchronization queue</Text><Text style={styles.settingText}>{syncSummary.pending} pending change{syncSummary.pending === 1 ? "" : "s"}; conflicts always require an explicit technician choice.</Text></View></View>{isAuthenticated ? <Pressable onPress={() => logout()} style={({ pressed }) => [styles.signOutButton, pressed && styles.pressed]}><Text style={styles.signOutText}>Sign out</Text></Pressable> : <Pressable onPress={() => startOAuthLogin()} style={({ pressed }) => [styles.signInButton, pressed && styles.primaryPressed]}><Text style={styles.signInText}>Sign in to workspace</Text><IconSymbol name="chevron.right" size={18} color="#FFFFFF" /></Pressable>}</ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingBottom: 30 }, topBar: { paddingTop: 5 }, backButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E1EAEE", alignItems: "center", justifyContent: "center" }, eyebrow: { color: "#087E8B", fontSize: 11, fontWeight: "800", letterSpacing: 1.1, marginTop: 26 }, title: { color: "#123047", fontSize: 31, fontWeight: "800", lineHeight: 38, marginTop: 2 }, loader: { height: 100, alignItems: "center", justifyContent: "center" }, identityCard: { backgroundColor: "#123047", borderRadius: 17, padding: 17, flexDirection: "row", gap: 13, marginTop: 18, alignItems: "center" }, avatar: { width: 48, height: 48, borderRadius: 24, alignItems: "center", justifyContent: "center", backgroundColor: "#087E8B" }, identityCopy: { flex: 1 }, name: { color: "#FFFFFF", fontSize: 17, fontWeight: "800" }, email: { color: "#B8CDD9", fontSize: 12, lineHeight: 17, marginTop: 3 }, sectionTitle: { color: "#123047", fontSize: 18, fontWeight: "800", marginTop: 24, marginBottom: 9 }, settingCard: { backgroundColor: "#FFFFFF", borderRadius: 15, padding: 14, borderWidth: 1, borderColor: "#E1EAEE", flexDirection: "row", gap: 11, marginBottom: 9 }, settingIcon: { width: 34, height: 34, borderRadius: 17, backgroundColor: "#E9F7F7", alignItems: "center", justifyContent: "center" }, settingCopy: { flex: 1 }, settingTitle: { color: "#123047", fontSize: 14, fontWeight: "800" }, settingText: { color: "#64748B", fontSize: 12, lineHeight: 17, marginTop: 2 }, signOutButton: { minHeight: 52, borderRadius: 14, borderWidth: 1, borderColor: "#E5A4A0", alignItems: "center", justifyContent: "center", marginTop: 20 }, signOutText: { color: "#B42318", fontSize: 15, fontWeight: "800" }, signInButton: { minHeight: 52, borderRadius: 14, backgroundColor: "#087E8B", flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 7, marginTop: 20 }, signInText: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" }, pressed: { opacity: 0.64 }, primaryPressed: { opacity: 0.84, transform: [{ scale: 0.98 }] } });
