import { useMemo } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { StatusPill } from "@/components/field-service/status-pill";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { useFieldService } from "@/lib/field-service/field-service-provider";

function formatAppointment(value: string) { return new Intl.DateTimeFormat(undefined, { weekday: "short", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)); }
export default function WorkOrderDetailScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id: string }>(); const { ready, workOrders, getVisitForOrder, startVisit, setWorkOrderConflict } = useFieldService(); const workOrder = useMemo(() => workOrders.find((item) => item.id === id), [id, workOrders]); const visit = workOrder ? getVisitForOrder(workOrder.id) : undefined;
  if (!ready) return <ScreenContainer className="items-center justify-center"><ActivityIndicator size="large" color="#087E8B" /></ScreenContainer>;
  if (!workOrder) return <ScreenContainer className="items-center justify-center p-6"><Text style={styles.notFound}>This work order is no longer available on this device.</Text></ScreenContainer>;
  const openVisit = async () => { if (!visit) await startVisit(workOrder.id); router.push({ pathname: "/visit/[id]", params: { id: workOrder.id } }); };
  return <ScreenContainer containerClassName="bg-[#F5F8FA]" className="bg-[#F5F8FA]" edges={["top", "left", "right", "bottom"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.topBar}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.backButton, pressed && styles.pressed]}><IconSymbol name="arrow.left" size={21} color="#123047" /></Pressable><Pressable onPress={() => setWorkOrderConflict(workOrder.id)} style={({ pressed }) => [styles.conflictButton, pressed && styles.pressed]}><Text style={styles.conflictText}>Simulate conflict</Text></Pressable></View><View style={styles.hero}><View style={styles.badges}><StatusPill value={workOrder.status} />{workOrder.priority === "urgent" ? <StatusPill value={workOrder.priority} /> : null}</View><Text style={styles.customer}>{workOrder.customerName}</Text><Text style={styles.site}>{workOrder.serviceSite}</Text></View><View style={styles.infoCard}><View style={styles.infoRow}><IconSymbol name="calendar" size={18} color="#087E8B" /><View><Text style={styles.infoLabel}>Scheduled visit</Text><Text style={styles.infoValue}>{formatAppointment(workOrder.scheduledStart)}</Text></View></View><View style={styles.rowDivider} /><View style={styles.infoRow}><IconSymbol name="location.fill" size={18} color="#087E8B" /><View><Text style={styles.infoLabel}>Service location</Text><Text style={styles.infoValue}>{workOrder.address}</Text></View></View></View><Text style={styles.sectionTitle}>Service scope</Text><View style={styles.card}><Text style={styles.description}>{workOrder.description}</Text><View style={styles.equipmentRow}><IconSymbol name="wrench.and.screwdriver.fill" size={16} color="#64748B" /><Text style={styles.equipment}>{workOrder.equipment}</Text></View></View><Text style={styles.sectionTitle}>Visit progress</Text><View style={styles.card}><View style={styles.progressHeader}><View style={styles.progressCopy}><Text style={styles.progressTitle}>{visit?.completedAt ? "Service report complete" : visit?.startedAt ? "Visit in progress" : "Visit not started"}</Text><Text style={styles.progressText}>{visit?.updatedAt ? `Last saved ${new Intl.DateTimeFormat(undefined, { hour: "numeric", minute: "2-digit" }).format(new Date(visit.updatedAt))} on this device` : "Start the visit when you arrive on site."}</Text></View><IconSymbol name={visit?.completedAt ? "checkmark.circle.fill" : "doc.text.fill"} size={24} color={visit?.completedAt ? "#197A42" : "#087E8B"} /></View></View><Pressable onPress={openVisit} style={({ pressed }) => [styles.primaryButton, pressed && styles.primaryPressed]}><Text style={styles.primaryText}>{visit?.completedAt ? "View service report" : visit?.startedAt ? "Continue visit" : "Start visit"}</Text><IconSymbol name="chevron.right" size={19} color="#FFFFFF" /></Pressable></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingBottom: 28 }, topBar: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingTop: 5 }, backButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E1EAEE", alignItems: "center", justifyContent: "center" }, conflictButton: { paddingHorizontal: 10, paddingVertical: 8 }, conflictText: { color: "#B42318", fontSize: 12, fontWeight: "800" }, pressed: { opacity: 0.64 }, hero: { paddingTop: 25, paddingBottom: 18 }, badges: { flexDirection: "row", gap: 7, marginBottom: 12 }, customer: { color: "#123047", fontSize: 29, fontWeight: "800", lineHeight: 35 }, site: { color: "#64748B", fontSize: 16, marginTop: 4 }, infoCard: { backgroundColor: "#FFFFFF", borderRadius: 16, borderWidth: 1, borderColor: "#E1EAEE", paddingHorizontal: 15 }, infoRow: { flexDirection: "row", alignItems: "center", gap: 11, paddingVertical: 14 }, rowDivider: { height: 1, backgroundColor: "#EAF0F3", marginLeft: 29 }, infoLabel: { color: "#64748B", fontSize: 12, fontWeight: "700" }, infoValue: { color: "#123047", fontSize: 14, fontWeight: "700", marginTop: 2 }, sectionTitle: { color: "#123047", fontSize: 18, fontWeight: "800", marginTop: 24, marginBottom: 9 }, card: { backgroundColor: "#FFFFFF", borderRadius: 16, borderWidth: 1, borderColor: "#E1EAEE", padding: 15 }, description: { color: "#334155", fontSize: 14, lineHeight: 21 }, equipmentRow: { flexDirection: "row", gap: 7, alignItems: "center", marginTop: 13, paddingTop: 12, borderTopWidth: 1, borderTopColor: "#EAF0F3" }, equipment: { color: "#64748B", fontSize: 13, fontWeight: "700" }, progressHeader: { flexDirection: "row", justifyContent: "space-between", gap: 12, alignItems: "center" }, progressCopy: { flex: 1 }, progressTitle: { color: "#123047", fontSize: 15, fontWeight: "800" }, progressText: { color: "#64748B", fontSize: 12, lineHeight: 17, marginTop: 3 }, primaryButton: { marginTop: 18, minHeight: 52, borderRadius: 14, backgroundColor: "#087E8B", alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8 }, primaryPressed: { opacity: 0.84, transform: [{ scale: 0.98 }] }, primaryText: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" }, notFound: { color: "#64748B", fontSize: 15, textAlign: "center" } });
