import { useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { WorkOrderRow } from "@/components/field-service/work-order-row";
import { ScreenContainer } from "@/components/screen-container";
import { useFieldService } from "@/lib/field-service/field-service-provider";
import type { WorkOrderStatus } from "@/lib/field-service/types";

const filters: { label: string; value: "all" | WorkOrderStatus }[] = [{ label: "All", value: "all" }, { label: "Scheduled", value: "scheduled" }, { label: "In progress", value: "in_progress" }, { label: "Review", value: "needs_review" }, { label: "Complete", value: "completed" }];
export default function WorkOrdersScreen() {
  const router = useRouter(); const { ready, workOrders } = useFieldService(); const [selected, setSelected] = useState<(typeof filters)[number]["value"]>("all"); const visibleOrders = useMemo(() => selected === "all" ? workOrders : workOrders.filter((item) => item.status === selected), [selected, workOrders]);
  if (!ready) return <ScreenContainer className="items-center justify-center"><ActivityIndicator size="large" color="#087E8B" /></ScreenContainer>;
  return <ScreenContainer containerClassName="bg-[#F5F8FA]" className="bg-[#F5F8FA]"><View><View style={styles.header}><Text style={styles.eyebrow}>ASSIGNMENTS</Text><Text style={styles.title}>Work Orders</Text><Text style={styles.subtitle}>{visibleOrders.length} record{visibleOrders.length === 1 ? "" : "s"} in this view</Text></View><FlatList horizontal data={filters} keyExtractor={(item) => item.value} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filterContent} renderItem={({ item }) => <Pressable onPress={() => setSelected(item.value)} style={({ pressed }) => [styles.filter, selected === item.value && styles.filterActive, pressed && styles.pressed]}><Text style={[styles.filterText, selected === item.value && styles.filterTextActive]}>{item.label}</Text></Pressable>} /></View><FlatList data={visibleOrders} keyExtractor={(item) => item.id} renderItem={({ item }) => <WorkOrderRow item={item} onPress={() => router.push({ pathname: "/work-orders/[id]", params: { id: item.id } })} />} contentContainerStyle={styles.ordersContent} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyText}>No work orders match this status.</Text></View>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ header: { paddingHorizontal: 20, paddingTop: 14, paddingBottom: 8 }, eyebrow: { color: "#087E8B", fontSize: 11, fontWeight: "800", letterSpacing: 1.2 }, title: { color: "#123047", fontSize: 31, fontWeight: "800", lineHeight: 38, marginTop: 2 }, subtitle: { color: "#64748B", fontSize: 14, marginTop: 2 }, filterContent: { paddingHorizontal: 20, gap: 8, paddingTop: 6, paddingBottom: 13 }, filter: { paddingHorizontal: 13, paddingVertical: 8, borderRadius: 999, borderWidth: 1, borderColor: "#CFDEE5", backgroundColor: "#FFFFFF" }, filterActive: { backgroundColor: "#123047", borderColor: "#123047" }, filterText: { color: "#526575", fontSize: 13, fontWeight: "700" }, filterTextActive: { color: "#FFFFFF" }, pressed: { opacity: 0.65 }, ordersContent: { paddingBottom: 30 }, empty: { margin: 20, borderRadius: 16, backgroundColor: "#FFFFFF", padding: 20, alignItems: "center" }, emptyText: { color: "#64748B", fontSize: 14 } });
